#!/bin/bash

set -e

echo '+cargo +nightly sort --grouped --workspace --check'
cargo install cargo-sort
cargo +nightly sort --grouped --workspace --check
echo '+cargo +nightly fmt -- --check'
cargo +nightly fmt -- --check
echo '+cargo +nightly clippy -- -D warnings'
cargo +nightly clippy -- -D warnings
